title: "Minoxidilbg.com"
email: "minoxidilbg@gmail.com"
description: "Миноксидил продукт против косопад, разтвор 2% и 5% за мъже и жени. Всичко за третиране на косопад, алопеция и стимулиране на растежа на нова коса."
author: "Тел. 0878 914 807"
lang: "bg"
timezone: Europe/Sofia
url: "https://minoxidilbg.com"
baseurl: ""

# GitHub Pages (Jekyll 3.9) – безопасно:
permalink: pretty

theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# по избор; не пречи
keywords:
  - миноксидил
  - миноксидил 5%
  - миноксидил за мъже
  - миноксидил 2%
  - миноксидил за жени
  - лечение на косопад
  - андрогенна алопеция
  - растеж на косата
  - косопад при мъже
  - косопад при жени
  - локално приложение
  - резултати от миноксидил
  - миноксидилbg

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
 
