title: "Minoxidilbg"
email: "minoxidilbg@gmail.com"
description: "Миноксидил 2% и 5% за мъже и жени. Всичко за лечение на косопад, алопеция и стимулиране на растежа на нова коса."
author: "MinoxidilBG"
lang: "bg"
timezone: Europe/Sofia
baseurl: "/minoxidilbg" # остави празно, защото сайтът е на root
url: "https://lolopetrov.github.io"
permalink: /:year/:month/:day/:title:output_ext

seo:
  type: website
  name: "MinoxidilBG"
  description: "Миноксидил срещу косопад за мъже и жени"
  twitter:
    username: "minoxidilbg"
  facebook:
    app_id: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
