title: "Миноксидил в България – 2% и 5% разтвор за жени и мъже | MinoxidilBG"
email: "minoxidilbg@gmail.com"
description: "Купете Миноксидил в България – 2% и 5% разтвор за мъже и жени. Клинично доказано решение срещу косопад, бърза доставка до всеки град в страната."
author: "Тел. 0878 914 807"
lang: "bg"
timezone: Europe/Sofia
url: "https://minoxidilbg.com"
baseurl: ""

permalink: "/:year/:month/:day/:title:output_ext"  # по избор; влияе на постове, не на страници


theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
