title: "Minoxidilbg.com"
email: "minoxidilbg@gmail.com"
description: "Миноксидил продукт против косопад, разтвор 2% и 5% за мъже и жени. Всичко за третиране на косопад, алопеция и стимулиране на растежа на нова коса."
author: "Тел. 0878 914 807"
lang: "bg"
timezone: Europe/Sofia
url: "https://minoxidilbg.com"
baseurl: ""

permalink: pretty

theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
